dist: bionic
script:
  - curl -LO https://github.com/rust-lang-nursery/mdBook/releases/download/v0.3.1/mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz
  - tar xf ./mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz
  - chmod +x ./mdbook
  - ./mdbook build

deploy:
  local_dir: docs
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
