language: rust
script:
  - curl -O https://github.com/rust-lang-nursery/mdBook/releases/download/v0.3.1/mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz
  - tar xzf ./mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz
  - chmod +x ./mdbook
  - ./mdbook build
